#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import getopt
import xmlrpc.client as XC

s = XC.ServerProxy('http://localhost:6800/rpc')


def help():
    print(
        "Usage: {0} [-i torrent/Uri] [-o output directory (optional)]".format(
            __file__))


def setMode(iUrl):
    if iUrl:
        # default
        mode = 1

        # torrent
        if os.path.isfile(iUrl):
            f, e = os.path.splitext(iUrl)
            if e == ".torrent":
                mode = 2
    return mode


def procArgs():

    outDir = os.getcwd()

    argv = sys.argv[1:]
    if not argv:
        help()

    try:
        opts, args = getopt.getopt(argv, "hi:o:", ["iurl=", "outDir="])
    except getopt.GetoptError:
        help()
        sys.exit(2)

    if not opts:
        help()
        sys.exit()

    for opt, arg in opts:
        if opt == '-h':
            help()
            sys.exit()
        elif opt in ("-i", "--iUrl"):
            iUrl = arg
        elif opt in ("-o", "--outDir"):
            outDir = arg

    mode = setMode(iUrl)
    return mode, iUrl, outDir


def addTask(mode, iUrl, outDir):
    try:
        print("intput: {}".format(iUrl))
        print("outDir: {}".format(outDir))
        print("method: ", end="")
        if mode == 1:
            print("addUri")
            s.aria2.addUri([iUrl], dict(dir=outDir), 0)
        elif mode == 2:
            print("addTorrent")
            s.aria2.addTorrent(XC.Binary(open(iUrl, mode='rb').read()))
    except Exception as e:
        print(e)


def main():
    mode, iUrl, outDir = procArgs()
    addTask(mode, iUrl, outDir)


if __name__ == "__main__":
    main()
